name: 01-Basic-First-WorkFLow

on:
  workflow_dispatch   # manually trigger the workflow

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 1
        run: echo "Hello World"