name: 02 Basic Events

on:
  push:
    branches:   
      - master

# on:
#   [push ,pull_request]

# you can add multi events here as array
  # pull_request:
  #   types: [opened, synchronize, reopened]  

# you can add multi events here as list
    # types:  
    #   - closed
    #   - opened

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 2
        run: echo "Hello World"
