name: 06  Basics  Context

run-name: ${{github.actor}} Explaining context data - Try Numbe ${{github.run_number}}

on:
  workflow_dispatch
  # push:
  #   branches: [ 06-basics-context ]  # manually trigger the workflow

jobs:
  print-context-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context Data
        # run: echo ${{ github }}
        run: echo ${{ github.actor }}
        # run: echo ${{ github['actor'] }}
        # run: echo ${{ github.event_name }}
        # run: echo ${{ job.status }}
        # run: echo ${{ toJson(github) }} -- prints all the data in github context in json format 
        # run: echo ${{ toJson(github.event) }}
